### ISSUE TITLE
TinyMCE-Swing Integration zip file

### ISSUE THREAD

**Issue by SaiSriHarsha333** [tinymce/tinymce-swing-codesamples#6]
I'm trying to integrate TinyMCE in Swing window. Where can I find the mentioned TinyMCE-Swing Integration zip file?

Thanks

**Comment by EkimChau** [comment]
Hi SaiSriHarsha333,

Our Swing integration is a closed source project, to access our Beta integration zip please visit our support site and submit a technical support request with regards to your enquiry.

https://support.tiny.cloud/

Our support team will assist you from there, Thank you for your interest in TinyMCE Swing.
I will now close this ticket
